<a href="https://colab.research.google.com/github/Yukkitsune/TBank-Analytics/blob/main/Data%20processing%20using%20SQL%20and%20Python/trenazher_vvedenie_v_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Тренажёр. Введение в pandas

**Добро пожаловать в тренажёр!**

Здесь тебе предстоит решить шесть небольших дополнительных задач, которые помогут набить руку и закрепить материал недели.

Как работать с тренажёром:
- Ответь на вопросы, поставленные в задачах.
- В конце воркбука ты найдёшь ответы на задачи, чтобы проверить свои решения.

Время выполнения ~40 минут.

Удачи в решении задач и закреплении полученных знаний!

**Дано 5 списков:**

 1. *client_list* — список клиентов, которые совершали покупки.
 2. *points_list* — список торговых точек, в которых совершались операции.
 3. *pay_list* — список клиентских платежей.
 4. *date_pay_list* — список дат платежей.
 5. *comment_list* — список технических комментариев к клиентским операциям.

In [139]:
import pandas as pd

client_list = [111,112,113,114,115,116,117,118,119,120]
points_list = [1,2,3,4,3,3,2,1,2,3]
pay_list = [150,290,1000,1200,900,850,300,2000,2100,960]
date_pay_list = ['2025-01-06','2025-02-06','2025-01-15','2025-02-01','2025-01-13','2025-01-22','2025-01-06','2025-02-08','2025-02-09','2025-02-03']
comment_list = ['89169999999', 'dd15@gmail.com', '-', '--', '89179999999','ss13@gmail.com','sd1@gmail.com','Progr1','Progr2','Progr3']

### Задание 1

 1. Создай словарь, в котором ключами будут будущие названия колонок в таблице, а значениями — списки с&nbsp;соответствующими значениями колонок.

 2. Создай датафрейм с помощью словаря из первого пункта.

 3. Выведи количество столбцов и строк в датафрейме, а также типы данных колонок.

 4. Сделай поле с идентификатором клиента индексом датафрейма.

In [140]:
### Твой код здесь
data_dict = {
    'client_id': client_list,
    'point': points_list,
    'payment': pay_list,
    'payment_date': date_pay_list,
    'comment': comment_list
}
df = pd.DataFrame(data_dict)

In [141]:
df.head(3)

client_id  point  payment payment_date         comment
0        111      1      150   2025-01-06     89169999999
1        112      2      290   2025-02-06  dd15@gmail.com
2        113      3     1000   2025-01-15               -

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   client_id     10 non-null     int64 
 1   point         10 non-null     int64 
 2   payment       10 non-null     int64 
 3   payment_date  10 non-null     object
 4   comment       10 non-null     object
dtypes: int64(3), object(2)
memory usage: 532.0+ bytes


In [ ]:
df.shape

(10, 5)

In [ ]:
df.dtypes

client_id        int64
point            int64
payment          int64
payment_date    object
comment         object
dtype: object

In [146]:
df.set_index('client_id', inplace=True)

In [147]:
df.head()

point  payment payment_date         comment
client_id                                             
111            1      150   2025-01-06     89169999999
112            2      290   2025-02-06  dd15@gmail.com
113            3     1000   2025-01-15               -
114            4     1200   2025-02-01              --
115            3      900   2025-01-13     89179999999

### Задание 2

Выведи все платежи строго больше $1000$ рублей, которые были произведены в торговых точках $1$ и $2$.

Отсортируй результат по платежу от большего к меньшему.

In [148]:
### Твой код здесь
df[(df['payment'] > 1000) & (df['point'].isin([1,2]))].sort_values(by='payment', ascending=True)

point  payment payment_date comment
client_id                                     
118            1     2000   2025-02-08  Progr1
119            2     2100   2025-02-09  Progr2

### Задание 3

Выведи самый большой платёж в торговой точке номер 3.

In [149]:
df

point  payment payment_date         comment
client_id                                             
111            1      150   2025-01-06     89169999999
112            2      290   2025-02-06  dd15@gmail.com
113            3     1000   2025-01-15               -
114            4     1200   2025-02-01              --
115            3      900   2025-01-13     89179999999
116            3      850   2025-01-22  ss13@gmail.com
117            2      300   2025-01-06   sd1@gmail.com
118            1     2000   2025-02-08          Progr1
119            2     2100   2025-02-09          Progr2
120            3      960   2025-02-03          Progr3

In [150]:
### Твой код здесь
df[df['point'] == 3].sort_values(by='payment', ascending=False).head(1)['payment']

client_id
113    1000
Name: payment, dtype: int64

### Задание 4

 1. С помощью функции *loc* выведи платежи и комментарии, соответствующие идентификаторам клиента $112$ и $113$.

 2. Сделай то же самое с помощью функции *iloc*.

 3. Убедись, что вывод получается одинаковый.

In [151]:
### Твой код здесь
df.loc[[112,113]][['payment','comment']]

payment         comment
client_id                         
112            290  dd15@gmail.com
113           1000               -

In [152]:
df.iloc[[1,2],[1,3]]

payment         comment
client_id                         
112            290  dd15@gmail.com
113           1000               -

In [153]:
df.iloc[1:3, 2:4]

payment_date         comment
client_id                             
112         2025-02-06  dd15@gmail.com
113         2025-01-15               -

### Задание 5

 1. Приведи столбец с датой платежа к формату даты.

 2. Создай в датафрейме новый столбец с датой платежа, приведённой к началу месяца.

 3. Создай в датафрейме новый столбец с номерами месяца.

In [155]:
### Твой код здесь
df['payment_date'] = pd.to_datetime(df['payment_date'])

point  payment payment_date         comment
client_id                                             
111            1      150   2025-01-06     89169999999
112            2      290   2025-02-06  dd15@gmail.com
113            3     1000   2025-01-15               -
114            4     1200   2025-02-01              --
115            3      900   2025-01-13     89179999999
116            3      850   2025-01-22  ss13@gmail.com
117            2      300   2025-01-06   sd1@gmail.com
118            1     2000   2025-02-08          Progr1
119            2     2100   2025-02-09          Progr2
120            3      960   2025-02-03          Progr3

In [157]:
df['start_date'] = df['payment_date'] + pd.offsets.MonthBegin(-1)
df

point  payment payment_date         comment start_date
client_id                                                        
111            1      150   2025-01-06     89169999999 2025-01-01
112            2      290   2025-02-06  dd15@gmail.com 2025-02-01
113            3     1000   2025-01-15               - 2025-01-01
114            4     1200   2025-02-01              -- 2025-01-01
115            3      900   2025-01-13     89179999999 2025-01-01
116            3      850   2025-01-22  ss13@gmail.com 2025-01-01
117            2      300   2025-01-06   sd1@gmail.com 2025-01-01
118            1     2000   2025-02-08          Progr1 2025-02-01
119            2     2100   2025-02-09          Progr2 2025-02-01
120            3      960   2025-02-03          Progr3 2025-02-01

In [158]:
df['month'] = df['payment_date'].dt.month
df

point  payment payment_date         comment start_date  month
client_id                                                               
111            1      150   2025-01-06     89169999999 2025-01-01      1
112            2      290   2025-02-06  dd15@gmail.com 2025-02-01      2
113            3     1000   2025-01-15               - 2025-01-01      1
114            4     1200   2025-02-01              -- 2025-01-01      2
115            3      900   2025-01-13     89179999999 2025-01-01      1
116            3      850   2025-01-22  ss13@gmail.com 2025-01-01      1
117            2      300   2025-01-06   sd1@gmail.com 2025-01-01      1
118            1     2000   2025-02-08          Progr1 2025-02-01      2
119            2     2100   2025-02-09          Progr2 2025-02-01      2
120            3      960   2025-02-03          Progr3 2025-02-01      2

### Задание 6

 1. Выведи строки, в которых комментарий представляет собой адрес электронной почты (проверка по содержанию символа собаки).

 2. Выведи строки, в которых комментарий представляет собой номер телефона (проверка по содержанию последовательности из 11 цифр).

 3. Выведи строки, в которых комментарий представляет собой номер программы сотрудничества (проверка по содержанию подстроки Progr).

In [159]:
### Твой код здесь
df[df['comment'].str.contains('@')]

point  payment payment_date         comment start_date  month
client_id                                                               
112            2      290   2025-02-06  dd15@gmail.com 2025-02-01      2
116            3      850   2025-01-22  ss13@gmail.com 2025-01-01      1
117            2      300   2025-01-06   sd1@gmail.com 2025-01-01      1

In [161]:
df[df['comment'].str.len() == 11]

point  payment payment_date      comment start_date  month
client_id                                                            
111            1      150   2025-01-06  89169999999 2025-01-01      1
115            3      900   2025-01-13  89179999999 2025-01-01      1

In [163]:
df[df['comment'].str.contains('\d{11}')]

<>:1: SyntaxWarning: invalid escape sequence '\d'
<>:1: SyntaxWarning: invalid escape sequence '\d'
/tmp/ipython-input-159446673.py:1: SyntaxWarning: invalid escape sequence '\d'
  df[df['comment'].str.contains('\d{11}')]


point  payment payment_date      comment start_date  month
client_id                                                            
111            1      150   2025-01-06  89169999999 2025-01-01      1
115            3      900   2025-01-13  89179999999 2025-01-01      1

In [162]:
df[df['comment'].str.contains('Progr')]

point  payment payment_date comment start_date  month
client_id                                                       
118            1     2000   2025-02-08  Progr1 2025-02-01      2
119            2     2100   2025-02-09  Progr2 2025-02-01      2
120            3      960   2025-02-03  Progr3 2025-02-01      2

# Ответы

### Задание 1

In [ ]:
dict_data = {  'id_client':client_list
             , 'id_point': points_list
             , 'amt_pay': pay_list
             , 'date_pay': date_pay_list
             , 'comment': comment_list
            }
df=pd.DataFrame(dict_data)

df.shape

(10, 5)

In [ ]:
df.dtypes

id_client     int64
id_point      int64
amt_pay       int64
date_pay     object
comment      object
dtype: object

In [ ]:
df.set_index('id_client', inplace = True)

df.head(3)

id_point  amt_pay    date_pay         comment
id_client                                               
111               1      150  2025-01-06     89169999999
112               2      290  2025-02-06  dd15@gmail.com
113               3     1000  2025-01-15               -

### Задание 2

In [ ]:
df[(df['amt_pay']>1000) & (df['id_point']<=2)].sort_values('amt_pay', ascending = False)

id_point  amt_pay    date_pay comment
id_client                                       
119               2     2100  2025-02-09  Progr2
118               1     2000  2025-02-08  Progr1

### Задание 3

In [ ]:
df[df['id_point']==3].sort_values('amt_pay', ascending = False).head(1)['amt_pay']

id_client
113    1000
Name: amt_pay, dtype: int64

### Задание 4

In [ ]:
df.loc[[112,113],['amt_pay','comment']]

amt_pay         comment
id_client                         
112            290  dd15@gmail.com
113           1000               -

In [ ]:
df.iloc[[1,2],[1,3]]

amt_pay         comment
id_client                         
112            290  dd15@gmail.com
113           1000               -

### Задание 5

In [ ]:
df['date_pay'] = pd.to_datetime(df['date_pay'])

df['month_int'] = df['date_pay'].dt.month
df['month_dat'] = df['date_pay'].dt.to_period('M').dt.to_timestamp()

df.head(3)

id_point  amt_pay   date_pay         comment  month_int  month_dat
id_client                                                                    
111               1      150 2025-01-06     89169999999          1 2025-01-01
112               2      290 2025-02-06  dd15@gmail.com          2 2025-02-01
113               3     1000 2025-01-15               -          1 2025-01-01

### Задание 6

In [ ]:
df[df['comment'].str.contains('@')]

id_point  amt_pay   date_pay         comment  month_int  month_dat
id_client                                                                    
112               2      290 2025-02-06  dd15@gmail.com          2 2025-02-01
116               3      850 2025-01-22  ss13@gmail.com          1 2025-01-01
117               2      300 2025-01-06   sd1@gmail.com          1 2025-01-01

In [ ]:
df[df['comment'].str.contains('\d{11}')]

<>:1: SyntaxWarning: invalid escape sequence '\d'
<>:1: SyntaxWarning: invalid escape sequence '\d'
/tmp/ipython-input-159446673.py:1: SyntaxWarning: invalid escape sequence '\d'
  df[df['comment'].str.contains('\d{11}')]


id_point  amt_pay   date_pay      comment  month_int  month_dat
id_client                                                                 
111               1      150 2025-01-06  89169999999          1 2025-01-01
115               3      900 2025-01-13  89179999999          1 2025-01-01

In [ ]:
df[df['comment'].str.contains('Progr')]

id_point  amt_pay   date_pay comment  month_int  month_dat
id_client                                                            
118               1     2000 2025-02-08  Progr1          2 2025-02-01
119               2     2100 2025-02-09  Progr2          2 2025-02-01
120               3      960 2025-02-03  Progr3          2 2025-02-01